[package]
name = "url"
description = "A fast, standards-compliant WHATWG URL parser in pure Nim"
version = "0.1.5"
license = "BSD-3-Clause"
kind = "Library"
backend = "C"
binaries = []

[toolchain]
version = "2.2.0"

[dependencies]
benchy = ">= 0.0.1"
shakar = ">= 0.1.3"
results = ">= 0.5.1"
pretty = ">= 0.2.0"
"gh:xTrayambak/overdrive" = ">= 0.1.1"
