name: x64 Testing
on: push

jobs:
  builds:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble install
      - run: nimble test
