name: x64 Testing
on: push

jobs:
  builds:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache nimble
        id: cache-nim
        uses: actions/cache@v4
        with:
          path: .nim_runtime
          key: ${{ runner.os }}-nimble-x64-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-${{ runner.arch }}-
       
      - name: Setup Nim
        if: steps.cache-nim.outputs.cache-hit != 'true'
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache nimble packages
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.nim_runtime/bin
          key: ${{ runner.os }}-nimble-${{ runner.arch }}-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-${{ runner.arch }}-

      - name: Ensure Nim is in PATH
        run: |
          echo "${{ github.workspace }}/.nim_runtime/bin" >> $GITHUB_PATH

      - name: Install nim-url
        run: nimble install -y

      - name: Run test suite (SSE2)
        run: echo "-d:sse2" > nim.cfg && nimble test

      - name: Run test suite (SSE3)
        run: echo "-d:sse3" > nim.cfg && nimble test

      - name: Run test suite (SSE4.1)
        run: echo "-d:sse41" > nim.cfg && nimble test

      - name: Run test suite (AVX2)
        run: echo -e "-d:avx2" > nim.cfg && nimble test
