name: x64 Testing
on: push

jobs:
  builds:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache nimble
        id: cache-nim
        uses: actions/cache@v4
        with:
          path: .nim_runtime
          key: ${{ runner.os }}-nimble-x64-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-
       
      - name: Setup Nim
        if: steps.cache-nim.outputs.cache-hit != 'true'
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install nim-url
        run: nimble install

      - name: Run test suite
        run: nimble test
